import { Comic, User } from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    email: "demo@example.com",
    name: "Demo User",
    persona: {
      storyEndingPreference: "Love wins",
      justiceOrMercy: "Mercy",
      planOrMess: "Glorious Mess",
      riskOrFaith: "Leap of Faith",
      twistOrPayoff: "Satisfying Payoff",
      hopeOrHonesty: "Unshakeable Hope",
      greaterGoodOrPersonalBond: "Personal Bond",
      vibes: ["Cozy & Heartwarming", "Witty & Charming"],
      favoriteTwist: "Identity reveal",
      personaType: "The Dreamer",
    },
    favorites: ["1", "3"],
    history: [
      {
        comicId: "1",
        lastReadPage: 3,
        lastReadAt: "2025-06-17T14:30:00Z",
        progress: 30,
      },
      {
        comicId: "2",
        lastReadPage: 1,
        lastReadAt: "2025-06-16T09:15:00Z",
        progress: 10,
      },
    ],
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "u2",
    email: "user@test.com",
    name: "Test User",
    persona: {
      storyEndingPreference: "Justice served",
      justiceOrMercy: "Justice",
      planOrMess: "Perfect Plan",
      riskOrFaith: "Calculated Risk",
      twistOrPayoff: "Shocking Twist",
      hopeOrHonesty: "Brutal Honesty",
      greaterGoodOrPersonalBond: "Greater Good",
      vibes: ["Dark & Brooding", "Action-Packed & Thrilling"],
      favoriteTwist: "Hidden betrayal",
      personaType: "The Strategist",
    },
    favorites: ["2", "4"],
    history: [
      {
        comicId: "4",
        lastReadPage: 5,
        lastReadAt: "2025-06-18T10:45:00Z",
        progress: 50,
      },
    ],
    createdAt: "2025-02-15T00:00:00Z",
  },
];

export const MOCK_COMICS: Comic[] = [
  {
    id: "1",
    title: "The Last Guardian",
    description:
      "An epic tale of a young warrior tasked with protecting the last magical creature in the realm.",
    posterImage: "/comics/comic1.jpg",
    categories: ["Fantasy", "Adventure", "Epic & Grandiose"],
    hasAudio: true,
    hasImages: true,
    releaseDate: "2024-01-15",
    popularity: 95,
    rating: 4.8,
  },
  {
    id: "2",
    title: "Midnight Chronicles",
    description:
      "A dark detective story set in a dystopian future where night never ends.",
    posterImage: "/comics/comic2.jpg",
    categories: ["Noir", "Mystery", "Dark & Brooding"],
    hasAudio: true,
    hasImages: true,
    releaseDate: "2024-02-23",
    popularity: 87,
    rating: 4.5,
  },
  {
    id: "3",
    title: "Hearth & Home",
    description:
      "A slice-of-life story about finding peace and connection in a small magical village.",
    posterImage: "/comics/comic3.jpg",
    categories: ["Slice of Life", "Fantasy", "Cozy & Heartwarming"],
    hasAudio: false,
    hasImages: true,
    releaseDate: "2024-03-10",
    popularity: 82,
    rating: 4.7,
  },
  {
    id: "4",
    title: "Quantum Break",
    description:
      "When a physics experiment goes wrong, reality itself begins to fracture.",
    posterImage: "/comics/comic4.jpg",
    categories: ["Sci-Fi", "Thriller", "Mind-Bending & Mysterious"],
    hasAudio: true,
    hasImages: true,
    releaseDate: "2024-04-05",
    popularity: 91,
    rating: 4.6,
  },
  {
    id: "5",
    title: "The Jester's Court",
    description:
      "A witty tale of political intrigue told from the perspective of a royal jester.",
    posterImage: "/comics/comic5.jpg",
    categories: ["Comedy", "Historical", "Witty & Charming"],
    hasAudio: false,
    hasImages: true,
    releaseDate: "2024-05-12",
    popularity: 79,
    rating: 4.3,
  },
  {
    id: "6",
    title: "Final Stand",
    description:
      "The heart-wrenching story of the last survivors of a galactic war.",
    posterImage: "/comics/comic6.jpg",
    categories: ["Sci-Fi", "Drama", "Tragic & Cathartic"],
    hasAudio: true,
    hasImages: true,
    releaseDate: "2024-06-20",
    popularity: 88,
    rating: 4.9,
  },
  {
    id: "7",
    title: "Velocity",
    description:
      "A high-octane story about underground racing and the dangerous world it inhabits.",
    posterImage: "/comics/comic7.jpg",
    categories: ["Action", "Thriller", "Action-Packed & Thrilling"],
    hasAudio: true,
    hasImages: true,
    releaseDate: "2024-07-07",
    popularity: 93,
    rating: 4.4,
  },
  {
    id: "8",
    title: "Shadow Twins",
    description:
      "A woman discovers her long-lost twin is living in a parallel dimension.",
    posterImage: "/comics/comic8.jpg",
    categories: ["Drama", "Sci-Fi", "Identity reveal"],
    hasAudio: false,
    hasImages: true,
    releaseDate: "2024-08-14",
    popularity: 85,
    rating: 4.5,
  },
  {
    id: "9",
    title: "Betrayal's Price",
    description: "A royal advisor plots against the throne, but at what cost?",
    posterImage: "/comics/comic9.jpg",
    categories: ["Fantasy", "Drama", "Hidden betrayal"],
    hasAudio: true,
    hasImages: true,
    releaseDate: "2024-09-02",
    popularity: 89,
    rating: 4.7,
  },
  {
    id: "10",
    title: "Time Fracture",
    description:
      "When the timeline splinters, a historian must put it back together.",
    posterImage: "/comics/comic10.jpg",
    categories: ["Sci-Fi", "Adventure", "Time/reality bend"],
    hasAudio: true,
    hasImages: true,
    releaseDate: "2024-10-18",
    popularity: 90,
    rating: 4.6,
  },
  {
    id: "11",
    title: "The Long Con",
    description:
      "A con artist finally meets his match when he targets the wrong mark.",
    posterImage: "/comics/comic11.jpg",
    categories: ["Crime", "Thriller", "Karma hits hard"],
    hasAudio: true,
    hasImages: true,
    releaseDate: "2024-11-25",
    popularity: 86,
    rating: 4.8,
  },
  {
    id: "12",
    title: "Eternal Love",
    description: "A romance that spans centuries and multiple lifetimes.",
    posterImage: "/comics/comic12.jpg",
    categories: ["Romance", "Fantasy", "Love wins"],
    hasAudio: false,
    hasImages: true,
    releaseDate: "2024-12-10",
    popularity: 92,
    rating: 4.9,
  },
];
